README.md, app/controllers/application_controller.rb, app/controllers/user_sessions_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/helpers/team_helper.rb, app/services/team_registrar.rb, app/views/dashboard/show.html.slim, app/views/shared/_external_login_buttons.html.slim, app/views/shared/_integrate_workspace.html.slim, app/views/teams/edit.html.slim, app/views/user_mailer/reset_password.html.slim, app/views/user_mailer/reset_password.text.slim, app/views/user_mailer/verification_required.html.slim, app/views/user_mailer/verification_required.text.slim, app/views/user_mailer/verified.html.slim, app/views/user_mailer/verified.text.slim, app/views/user_sessions/new.html.slim, app/views/users/new.html.slim, app/webpacker/packs/admin.js, config/application.rb, config/locales/en/auth.yml, config/locales/en/teams.yml, package.json, spec/services/team_registrar_spec.rb, yarn.lock
=> Add max_teams and user_email_domains, reduce README, yarn update

app/controllers/application_controller.rb, app/controllers/dashboard_controller.rb, app/controllers/profiles_controller.rb, app/views/shared/_connect_profile.html.slim, config/application.rb, config/locales/en/profiles.yml
=> Add App.shared_admin option

app/models/tip.rb, app/services/base/post_service.rb, app/services/slack/channel_leave_service.rb, app/services/slack/channel_member_service.rb, app/services/slack/post_service.rb, app/services/tip_mention_service.rb, config/locales/en/errors.yml, spec/services/tip_mention_service_spec.rb
=> Improve error message when no tips generated

.github/workflows/draft_release.yml, .github/workflows/push_to_registry.yml, Gemfile.lock, app/models/team.rb, app/services/commands/help.rb, app/services/commands/settings.rb, config/application.rb, spec/services/commands/settings_spec.rb
* Add `Draft Release` Github Action
* Use `APP_DISPLAY_NAME` env var for app name to avoid `APP_NAME` conflict with Docker
* Improve help messaging
* Bundle update
=> Various minor improvements

app/controllers/emails_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/_basic_preferences.html.slim, app/views/users/new.html.slim, config/locales/en/users.yml, db/migrate/20210915203423_remove_subscribe_newsletter_from_users.rb, db/schema.rb
Newsletter subscription was a carryover from KarmaChest SaaS implementation.
=> Remove newsletter subscription

app/validators/recipient_not_a_bot_validator.rb, app/validators/recipient_not_deleted_validator.rb, app/validators/recipient_not_self_validator.rb, config/locales/en/models.yml, config/locales/en/profiles.yml, spec/validators/recipient_not_a_bot_validator_spec.rb, spec/validators/recipient_not_deleted_validator_spec.rb, spec/validators/recipient_not_self_validator_spec.rb
=> Improve error messaging

app/policies/profile_policy.rb, app/views/profiles/tiles/_leaderboard_rows.html.slim
=> Allow admins to view team profiles

app/controllers/hooks/slack/base_controller.rb, app/controllers/profiles_controller.rb, app/services/base/post_service.rb, app/services/commands/connect.rb, app/services/slack/modals/preferences.rb, app/services/slack/post_service.rb, app/services/tip_mention_service.rb, app/services/tip_response_service.rb, app/views/profiles/_tiles.html.slim, app/views/profiles/edit.html.slim, config/locales/en/profiles.yml, db/migrate/20210926122243_add_profile_options.rb, db/schema.rb, spec/services/commands/connect_spec.rb, spec/services/slack/post_service_spec.rb, spec/services/tip_mention_service_spec.rb
=> Add profile announcement options

app/services/team_reset_service.rb, spec/services/team_reset_service_spec.rb
Fixes #77 . Team reset worked fine in development 🤷
=> Do not DM users on stats reset

app/controllers/teams_controller.rb, app/models/team.rb, app/services/base/post_service.rb, app/services/discord/post_service.rb, app/services/image/tip_service.rb, app/services/slack/post_service.rb, app/services/tip_response_service.rb, app/views/teams/settings/_responses.html.slim, config/locales/en/teams.yml, db/migrate/20211004204717_add_show_note_in_log_to_teams.rb, db/schema.rb, spec/services/discord/post_service_spec.rb, spec/services/slack/post_service_spec.rb, spec/services/tip_response_service_spec.rb
=> Add show_note option and improve response composition

app/services/leaderboard_service.rb, app/views/profiles/tiles/_leaderboard.html.slim, config/application.rb
=> Adjust max_points_per_tip and other config keys

app/services/base/post_service.rb, app/services/slack/post_service.rb, spec/services/slack/post_service_spec.rb
=> Use Slack conversations_replies endpoint to determine thread_ts

app/helpers/mail_helper.rb, app/helpers/profile_helper.rb, app/mailers/weekly_report_mailer.rb, app/services/commands/leaderboard.rb, app/services/reports/base_digest_service.rb, app/services/reports/profile_digest_service.rb, app/services/reports/team_digest_service.rb, app/views/layouts/email.html.slim, app/views/weekly_report_mailer/_footer.html.slim, app/views/weekly_report_mailer/_footer.text.erb, app/views/weekly_report_mailer/_header.html.slim, app/views/weekly_report_mailer/_header.text.erb, app/views/weekly_report_mailer/_profile_digest.html.slim, app/views/weekly_report_mailer/_profile_digest.text.erb, app/views/weekly_report_mailer/_team_digest.html.slim, app/views/weekly_report_mailer/_team_digest.text.erb, app/views/weekly_report_mailer/profile_report.html.slim, app/views/weekly_report_mailer/profile_report.text.erb, app/views/weekly_report_mailer/team_report.html.slim, app/views/weekly_report_mailer/team_report.text.erb, app/workers/weekly_report/profile_worker.rb, app/workers/weekly_report/team_worker.rb, spec/services/reports/profile_digest_service_spec.rb, spec/services/reports/team_digest_service_spec.rb
=> Improve weekly email reports

README.md, app/helpers/tip_helper.rb, app/services/actions/reaction_added.rb, app/services/tip_factory.rb, app/services/tip_mention_service.rb, app/views/profiles/tiles/_recent_activity.html.slim, config/locales/en/tips.yml, db/migrate/20220121061441_add_chat_permalink_to_tip.rb, db/schema.rb, spec/services/actions/reaction_added_spec.rb, spec/services/tip_factory_spec.rb, spec/services/tip_mention_service_spec.rb
=> Permalinks

app/services/slack/channel_join_service.rb, app/services/slack/post_service.rb
=> Rescue Slack exceptions

app/controllers/hooks/slack/base_controller.rb, app/models/team.rb, app/services/discord/bot_event_service.rb, app/workers/event_worker.rb, spec/factories/team.rb, spec/workers/event_worker_spec.rb
Fixes #141 
I think Sidekiq doesn't like the BigDecimals, which are just fine. So we encode/decode JSON manually 🤷
=> Fix Sidekiq warning

.rubocop.yml, app/controllers/hooks/slack/base_controller.rb, app/controllers/hooks/slack/events_controller.rb, app/models/concerns/team_decorator.rb, app/models/team.rb, app/services/base/channel_member_service.rb, app/services/cache/team_config.rb, app/services/commands/base.rb, app/services/commands/help.rb, app/services/commands/leaderboard.rb, app/services/commands/report.rb, app/services/commands/stats.rb, app/services/discord/bot_event_service.rb, app/services/reports/base_digest_service.rb, app/services/reports/profile_digest_service.rb, app/services/reports/team_digest_service.rb, app/services/slack/modals/tip.rb, app/services/slack/slack_api.rb, app/views/weekly_report_mailer/_team_digest.text.erb, app/workers/weekly_report/profile_worker.rb, config/application.rb, spec/models/team_spec.rb, spec/services/cache/team_config_spec.rb, spec/services/commands/report_spec.rb, spec/services/commands/stats_spec.rb, spec/services/slack/slack_api_spec.rb, spec/services/tip_factory_spec.rb
Fixes #103 
Also:
* Refactor reports for performance
* Ensure uniqueness on team config cache using platform/RID combo
=> Add in-chat reports (part 1)

app/controllers/application_controller.rb, app/controllers/profiles_controller.rb, app/controllers/teams_controller.rb, app/models/concerns/profile_decorator.rb, app/services/cache/leaderboard.rb, app/services/commands/leaderboard.rb, app/services/image/leaderboard_service.rb, app/services/leaderboard_page_service.rb, app/services/reports/profile_digest_service.rb, app/services/tip_outcome_service.rb, app/workers/chat_permalink_worker.rb, app/workers/event_worker.rb, app/workers/leaderboard_refresh_worker.rb, config/application.rb, config/sidekiq.yml, lib/tasks/seeds.rake, spec/services/cache/leaderboard_spec.rb, spec/services/commands/leaderboard_spec.rb, spec/services/commands/stats_spec.rb, spec/services/leaderboard_page_service_spec.rb, spec/services/tip_mention_service_spec.rb, spec/services/tip_outcome_service_spec.rb, spec/workers/leaderboard_refresh_worker_spec.rb
=> Improve the leaderboard

app/services/message_scanner.rb, app/services/tip_response_service.rb, config/application.rb, spec/services/message_scanner_spec.rb
=> Improve note extraction

app/helpers/points_helper.rb, app/models/concerns/profile_decorator.rb, config/locales/en/number.yml
=> Humanize long numbers in Quiet Text with Stats theme
